import { CheckCircle2, Database, Download, HardDrive, History, RefreshCw, ServerCog, Trash2 } from "lucide-react"
import packageInfo from "../../package.json"
import { SettingsPanel } from "./SettingsPanel"
import type { DiagnosticLog, RuntimeHealth } from "./types"

export function SettingsPage({ health, refreshing, onRefresh, logs, onClearLogs, updateChecking, onCheckUpdate }: { health: RuntimeHealth | null; refreshing: boolean; onRefresh: () => void; logs: DiagnosticLog[]; onClearLogs: () => void; updateChecking: boolean; onCheckUpdate: () => void }) {
  const mediaReady = health?.mediaPipeline.status === "healthy"
  return <section className="diagnostics-page"><header className="page-title"><div><h1>设置与诊断</h1><p>管理模型连接，并检查本机媒体处理环境。</p></div></header><section className="about-update-panel"><div className="about-update-icon"><History size={19} /></div><div className="about-update-copy"><div><h2>关于与更新</h2><p>当前版本 v{packageInfo.version} · 稿件和密钥均保存在此设备。</p></div><dl><div><dt>更新方式</dt><dd>应用内下载安装</dd></div><div><dt>历史版本</dt><dd>GitHub Release 保留</dd></div></dl></div><button type="button" className="primary-command" onClick={onCheckUpdate} disabled={updateChecking}><Download size={14} />{updateChecking ? "正在检查..." : "检查更新"}</button></section><SettingsPanel onSettingsChanged={onRefresh} /><section className="diagnostics-section"><header><div><h2>系统诊断</h2><p>确认浏览器、转写与媒体处理工具是否可以正常工作。</p></div><button type="button" className="secondary-command" onClick={onRefresh} disabled={refreshing}><RefreshCw size={14} />{refreshing ? "检测中..." : "重新检测环境"}</button></header><div className="diagnostic-overview"><div><Database size={18} /><span>本机运行状态</span><strong>{health?.mode === "native" ? "桌面应用正在运行" : "浏览器预览"}</strong></div><div><HardDrive size={18} /><span>稿件存储</span><strong>仅保存在此设备</strong></div><div><CheckCircle2 size={18} /><span>媒体处理</span><strong>{mediaReady ? "已就绪" : "需要检查"}</strong></div></div></section><details className="runtime-log-panel"><summary><div><h2>运行日志</h2><p>仅在排查问题时查看，内容已脱敏。</p></div><span className="log-summary-action"><History size={14} />查看日志</span></summary><div className="runtime-log-content"><button type="button" className="icon-command" title="清空日志" onClick={onClearLogs} disabled={!logs.length}><Trash2 size={14} /></button>{logs.length ? <div className="runtime-log-list">{logs.slice(0, 20).map((log) => <details key={log.id}><summary><span className="log-status"><ServerCog size={14} /></span><div><strong>{log.message}</strong><small>{new Date(log.createdAt).toLocaleString("zh-CN")} · {log.action}</small></div><code>{log.code}</code></summary><div className="runtime-log-detail">{log.detail ?? "无额外详情"}</div></details>)}</div> : <div className="runtime-log-empty">尚无运行日志。</div>}</div></details></section>
}
