import { useCallback, useEffect, useState } from "react"
import { DepositPage } from "./DepositPage"
import { TranscriptHistoryPage } from "./TranscriptHistoryPage"
import { SettingsPage } from "./SettingsPage"
import { WorkbenchShell } from "./Shell"
import { skillWorkbenchBridge } from "./skillWorkbenchBridge"
import { formatTranscript } from "./transcriptFormatting"
import type { DiagnosticLog, RecognitionPage, RecognitionSession, RuntimeHealth, SourceRecord, TranscriptRecord } from "./types"
import { UpdateDialog } from "./UpdateDialog"
import type { AppUpdateInfo } from "./types"
import "./skill-workbench.css"

function emptySession(): RecognitionSession { return { stage: "awaiting_source", source: null, transcript: "", transcriptQuality: "unavailable", proofread: null, events: [] } }
function sourceSession(source: SourceRecord, stage: RecognitionSession["stage"], transcript = ""): RecognitionSession { return { stage, source, transcript, transcriptQuality: transcript ? "needs_review" : "unavailable", proofread: null, events: [] } }

export default function SkillWorkbench() {
  const [page, setPage] = useState<RecognitionPage>("recognize"), [session, setSession] = useState<RecognitionSession>(emptySession), [records, setRecords] = useState<TranscriptRecord[]>([]), [ready, setReady] = useState(false), [notice, setNotice] = useState<string | null>(null), [health, setHealth] = useState<RuntimeHealth | null>(null), [healthRefreshing, setHealthRefreshing] = useState(false), [processing, setProcessing] = useState(false), [progress, setProgress] = useState<string | null>(null), [progressStage, setProgressStage] = useState("idle"), [proofreading, setProofreading] = useState(false), [logs, setLogs] = useState<DiagnosticLog[]>([]), [update, setUpdate] = useState<AppUpdateInfo | null>(null), [updateChecking, setUpdateChecking] = useState(false)
  const errorMessage = (error: unknown) => error instanceof Error ? error.message : String(error)
  const refreshLogs = useCallback(async () => { try { setLogs(await skillWorkbenchBridge.listDiagnosticLogs()) } catch (error) { setNotice(`无法读取运行日志：${errorMessage(error)}`) } }, [])
  const log = useCallback(async (value: Partial<DiagnosticLog>) => { try { const saved = await skillWorkbenchBridge.recordDiagnosticLog({ traceId: `ui-${crypto.randomUUID()}`, ...value }); setLogs((current) => [saved, ...current.filter((item) => item.id !== saved.id)].slice(0, 100)) } catch { /* logging never blocks recognition */ } }, [])
  useEffect(() => { skillWorkbenchBridge.loadRecognition().then((saved) => { if (saved) { setSession(saved.session ?? emptySession()); setRecords(saved.records ?? []) } setReady(true) }).catch((error) => { setNotice(`无法读取本机状态：${errorMessage(error)}`); setReady(true) }) }, [])
  useEffect(() => { if (ready) skillWorkbenchBridge.saveRecognition({ session, records }).catch((error) => setNotice(`本机保存失败：${errorMessage(error)}`)) }, [ready, session, records])
  const refreshHealth = useCallback(() => { setHealthRefreshing(true); skillWorkbenchBridge.runtimeHealth().then(setHealth).catch((error) => setNotice(`系统诊断失败：${errorMessage(error)}`)).finally(() => { setHealthRefreshing(false); void refreshLogs() }) }, [refreshLogs])
  useEffect(() => { refreshHealth(); void refreshLogs() }, [refreshHealth, refreshLogs])
  useEffect(() => { let dispose: (() => void) | undefined; skillWorkbenchBridge.onMediaProgress((value) => { setProgress(value.message); setProgressStage(value.stage) }).then((unlisten) => { dispose = unlisten }); return () => dispose?.() }, [])
  const useSource = (source: SourceRecord, stage: RecognitionSession["stage"], transcript = "") => { setNotice(null); setSession(sourceSession(source, stage, transcript)) }
  const proofread = async (transcript: string) => { if (!transcript.trim()) return; setProofreading(true); setNotice(null); try { const review = await skillWorkbenchBridge.proofreadTranscript(transcript); setSession((current) => ({ ...current, transcriptQuality: "needs_review", proofread: review })); setNotice(review.corrections.length ? `AI 已识别 ${review.corrections.length} 处可确认修改，请审核后继续。` : "AI 已完成语义校对和自然分段，请审核稿件后继续。") } catch (error) { setNotice(`文本校对失败：${errorMessage(error)}`) } finally { setProofreading(false); void refreshLogs() } }
  const recognizeLink = async (value: string) => { const match = value.match(/https?:\/\/(?:[a-z0-9-]+\.)?douyin\.com\/[^\s]+/i); if (!match) { setNotice("没有识别到有效的 douyin.com 分享链接，来源未记录。"); return } const source: SourceRecord = { id: `source-${crypto.randomUUID()}`, mode: "douyin_link", label: "抖音分享来源", value: match[0], authorized: true, mediaLocalOnly: false, createdAt: new Date().toISOString() }; useSource(source, "source_verified"); setProcessing(true); setProgressStage("source"); setProgress("正在校验抖音来源"); try { const result = await skillWorkbenchBridge.processMedia("douyin_link", value); const transcript = formatTranscript(result.transcript); const readySource = { ...source, label: result.author ? `${result.title} · ${result.author}` : result.title, value: result.url ?? source.value }; useSource(readySource, "transcript_ready", transcript); setProgressStage("proofread"); setProgress("真实稿件已取得，正在进行 AI 校对"); await proofread(transcript) } catch (error) { useSource(source, "transcript_blocked"); setNotice(`真实稿件获取失败：${errorMessage(error)}`) } finally { setProcessing(false); setProgress(null); setProgressStage("idle"); void refreshLogs() } }
  const importMedia = async (file?: File) => { try { const source = await skillWorkbenchBridge.selectLocalMedia(file); if (!source) return; useSource(source, "source_verified"); setProcessing(true); setProgressStage("source"); setProgress("正在校验本机媒体"); const result = await skillWorkbenchBridge.processMedia("local_media", source.value); const transcript = formatTranscript(result.transcript); useSource({ ...source, label: result.title }, "transcript_ready", transcript); setProgressStage("proofread"); await proofread(transcript) } catch (error) { setSession((current) => current.source ? { ...current, stage: "transcript_blocked" } : current); setNotice(`媒体导入或转写失败：${errorMessage(error)}`) } finally { setProcessing(false); setProgress(null); setProgressStage("idle"); void refreshLogs() } }
  const useTranscript = async (transcript: string, label: string) => { const formatted = formatTranscript(transcript); const source: SourceRecord = { id: `source-${crypto.randomUUID()}`, mode: "verified_transcript", label: label.trim(), value: label.trim(), authorized: true, mediaLocalOnly: false, createdAt: new Date().toISOString() }; useSource(source, "transcript_ready", formatted); await proofread(formatted) }
  const confirm = (value: string) => { if (!session.source) return; const now = new Date().toISOString(); const record: TranscriptRecord = { id: `transcript-${crypto.randomUUID()}`, title: session.source.label || "确认稿", source: session.source, originalTranscript: session.transcript, confirmedTranscript: value.trim(), proofread: session.proofread, createdAt: now, updatedAt: now, exports: [] }; setRecords((current) => [record, ...current.filter((item) => item.id !== record.id)]); setSession((current) => ({ ...current, stage: "confirmed", transcript: value.trim(), transcriptQuality: "verified" })); setNotice("确认稿已保存到本机历史。"); void log({ action: "transcript.confirm", stage: "human_confirmation", status: "success", code: "TRANSCRIPT_CONFIRMED", message: "确认稿已保存", location: "SkillWorkbench.tsx:confirm", detail: `仅记录确认稿长度：${value.trim().length} 字。` }) }
  const openRecord = (record: TranscriptRecord) => { setSession({ stage: "confirmed", source: record.source, transcript: record.confirmedTranscript, transcriptQuality: "verified", proofread: record.proofread, events: [] }); setPage("recognize"); setNotice("已打开历史确认稿。") }
  const copyRecord = async (record: TranscriptRecord) => { await navigator.clipboard?.writeText(record.confirmedTranscript); setNotice("确认稿已复制。") }
  const exportRecord = async (record: TranscriptRecord, format: "txt" | "markdown") => { try { const exported = await skillWorkbenchBridge.exportTranscript(record, format); setRecords((current) => current.map((item) => item.id === record.id ? { ...item, exports: [...item.exports, exported], updatedAt: exported.exportedAt } : item)); setNotice(`已导出 ${format === "markdown" ? "Markdown" : "TXT"}：${exported.path}`) } catch (error) { setNotice(`导出失败：${errorMessage(error)}`) } }
  const exportCurrent = (format: "txt" | "markdown") => { const record = records.find((item) => item.confirmedTranscript === session.transcript && item.source.id === session.source?.id); if (record) void exportRecord(record, format); else if (session.source && session.stage === "confirmed") void exportRecord({ id: "current", title: session.source.label, source: session.source, originalTranscript: session.transcript, confirmedTranscript: session.transcript, proofread: session.proofread, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), exports: [] }, format) }
  const clearLogs = async () => { if (!window.confirm("清空全部运行日志？")) return; await skillWorkbenchBridge.clearDiagnosticLogs(); setLogs([]) }
  const checkForUpdate = async () => { setUpdateChecking(true); setNotice(null); try { const value = await skillWorkbenchBridge.checkForUpdate(); setUpdate(value); if (!value) setNotice("当前已经是最新版本。"); return value } catch (error) { setNotice(`检查更新失败：${errorMessage(error)}`); return null } finally { setUpdateChecking(false) } }
  return <WorkbenchShell page={page} onPageChange={(next) => { setNotice(null); setPage(next) }} onSettings={() => setPage("settings")}>
    {page === "recognize" ? <DepositPage session={session} notice={notice} processing={processing} progressMessage={progress} progressStage={progressStage} proofreading={proofreading} onRecognizeLink={recognizeLink} onImportMedia={importMedia} onUseTranscript={useTranscript} onUpdateTranscript={(value) => setSession((current) => ({ ...current, stage: "transcript_ready", transcript: value, proofread: null, transcriptQuality: "needs_review" }))} onProofread={() => void proofread(session.transcript)} onFinalizeProofread={confirm} onReset={() => { setSession(emptySession()); setNotice(null) }} onCopy={() => void copyRecord(records.find((item) => item.source.id === session.source?.id) ?? { id: "current", title: "确认稿", source: session.source!, originalTranscript: session.transcript, confirmedTranscript: session.transcript, proofread: session.proofread, createdAt: "", updatedAt: "", exports: [] })} onExport={exportCurrent} /> : null}
    {page === "history" ? <TranscriptHistoryPage records={records} onOpen={openRecord} onCopy={copyRecord} onExport={exportRecord} /> : null}
    {page === "settings" ? <SettingsPage health={health} refreshing={healthRefreshing} onRefresh={refreshHealth} logs={logs} onClearLogs={() => void clearLogs()} updateChecking={updateChecking} onCheckUpdate={() => void checkForUpdate()} /> : null}
    {update ? <UpdateDialog update={update} onClose={() => setUpdate(null)} onInstall={async () => { await skillWorkbenchBridge.installUpdate() }} /> : null}
  </WorkbenchShell>
}
