import { Clipboard, Download, FileText, Search } from "lucide-react"
import { useMemo, useState } from "react"
import type { TranscriptRecord } from "./types"

export function TranscriptHistoryPage({ records, onOpen, onCopy, onExport }: { records: TranscriptRecord[]; onOpen: (record: TranscriptRecord) => void; onCopy: (record: TranscriptRecord) => void; onExport: (record: TranscriptRecord, format: "txt" | "markdown") => void }) {
  const [query, setQuery] = useState("")
  const filtered = useMemo(() => records.filter((record) => `${record.title} ${record.source.label} ${record.confirmedTranscript}`.toLowerCase().includes(query.trim().toLowerCase())), [records, query])
  return <section className="library-page"><div className="page-title"><div><h1>稿件历史</h1><p>已人工确认的稿件只保存在本机，可重新打开或导出。</p></div><strong>{records.length} 份确认稿</strong></div><label className="library-toolbar"><Search size={15} /><input aria-label="搜索稿件历史" placeholder="搜索来源、标题或稿件内容" value={query} onChange={(event) => setQuery(event.target.value)} /></label>{filtered.length ? <div className="transcript-history-list">{filtered.map((record) => <article className="transcript-history-item" key={record.id}><div className="history-icon"><FileText size={17} /></div><div className="history-content"><h2>{record.title}</h2><p>{record.confirmedTranscript.slice(0, 180)}{record.confirmedTranscript.length > 180 ? "…" : ""}</p><small>{record.source.label} · {new Date(record.updatedAt).toLocaleString("zh-CN")}</small></div><div className="history-actions"><button type="button" className="icon-command" title="打开稿件" onClick={() => onOpen(record)}><FileText size={14} /></button><button type="button" className="icon-command" title="复制确认稿" onClick={() => onCopy(record)}><Clipboard size={14} /></button><button type="button" className="icon-command" title="导出 TXT" onClick={() => onExport(record, "txt")}><Download size={14} /></button></div></article>)}</div> : <div className="library-empty"><FileText size={24} /><strong>{records.length ? "没有匹配的稿件" : "还没有确认稿"}</strong><p>{records.length ? "换一个关键词试试。" : "完成一次 AI 校对并人工确认后，稿件会出现在这里。"}</p></div>}</section>
}
